server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:

  - job_name: cowrie
    static_configs:
      - targets:
          - localhost
        labels:
          job: cowrie
          __path__: /logs/cowrie/*

  - job_name: webapp
    static_configs:
      - targets:
          - localhost
        labels:
          job: webapp
          __path__: /logs/*.txt
